
TARGET := libboot_c

SOURCES := \
	dprintf.c \
	xprintf.c \
	cprintf.c \
	sprintf.c \
	malloc.c \
	memcmp.c \
	memcpy.c \
	memset.c \
	strcpy.c \
	strlen.c \
	strcmp.c \
	strstr.c \
	crypto.c \
	rsa.c \
	sha.c

CFLAGS := -g -W -Wall
CFLAGS += -march=armv5 -I../include

MKSTATICLIB := 1

include ../edam.mk
